from pydantic import BaseModel, Field, field_validator
from typing import List, Literal, Optional, Union, Dict, Any
import json

class GameAction(BaseModel):
    action: Literal[
        "HARVEST", "DECLARE_WAR", "PROPOSE_ALLIANCE", "ACCEPT_ALLIANCE", "CANCEL_ALLIANCE",
        "PROPOSE_TRADE", "ACCEPT_TRADE", "PROPOSE_RESEARCH", "ACCEPT_RESEARCH", 
        "MILITARY_STRIKE", "SABOTAGE", "SKIRMISH", "RESEARCH", "PURSUE_CIVIC",
        "PROPOSE_JOINT_WAR", "ACCEPT_JOINT_WAR", "INVEST",
        "PROPOSE_PEACE", "ACCEPT_PEACE"
    ] = Field(..., description="The command to execute.")
    target: Optional[Union[int, str]] = Field(
        None, 
        description="""The target of the action. 
        For HARVEST: 'GOLD', 'MANPOWER', 'PRODUCTION', 'SCIENCE', 'CIVICS'.
        For DECLARE_WAR, PROPOSE_*, ACCEPT_*, CANCEL_*, MILITARY_STRIKE, SABOTAGE, SKIRMISH: int (Target Nation ID).
        For RESEARCH: str (Tech Name).
        For PURSUE_CIVIC: str (Civic Name)."""
    )
    enemy: Optional[int] = Field(
        None,
        description="The secondary target strictly representing the enemy Nation ID when proposing or accepting a joint war."
    )
    
    @field_validator('target')
    @classmethod
    def validate_target(cls, v: Any, info: Any) -> Any:
        # info.data contains other fields initialized so far
        if hasattr(info, 'data'):
            data = info.data
        else:
            # Pydantic v1 vs v2 fallback
            data = getattr(info, 'data', {}) # fallback if v1 info is different
            
        action = data.get('action')
        if not action:
            return v
            
        if action == "HARVEST":
            val = str(v).upper()
            if val not in ["GOLD", "MANPOWER", "PRODUCTION", "SCIENCE", "CIVICS"]:
                raise ValueError(f"Invalid harvest target: {v}")
            return val
        elif action in ["DECLARE_WAR", "PROPOSE_ALLIANCE", "ACCEPT_ALLIANCE", "CANCEL_ALLIANCE",
                        "PROPOSE_TRADE", "ACCEPT_TRADE", "PROPOSE_RESEARCH", 
                        "ACCEPT_RESEARCH", "MILITARY_STRIKE", "SABOTAGE", "SKIRMISH",
                        "PROPOSE_JOINT_WAR", "ACCEPT_JOINT_WAR", "PROPOSE_PEACE", "ACCEPT_PEACE"]:
            try:
                return int(v)
            except (ValueError, TypeError):
                raise ValueError(f"Action {action} requires an integer Nation ID, got: {v}")
        elif action in ["RESEARCH", "PURSUE_CIVIC", "INVEST"]:
            if not isinstance(v, str) or not v.strip():
                raise ValueError(f"Action {action} requires a string target, got: {v}")
            return str(v)
            
        return v
        
    def to_engine_string(self) -> str:
        if self.action in ["PROPOSE_JOINT_WAR", "ACCEPT_JOINT_WAR"]:
             return f"{self.action} {self.target} {self.enemy}"
        elif self.target is not None:
            return f"{self.action} {self.target}"
        return self.action

class AgentTurnResponse(BaseModel):
    reasoning: str = Field(..., description="Your thought process leading to the chosen actions.")
    actions: List[GameAction] = Field(..., description="Actions you intend to take. Cannot exceed your max action points.")

def parse_agent_response(response_json: str) -> tuple[List[str], Optional[str]]:
    """
    Takes a JSON string generated by an LLM, parses/validates it.
    Returns (engine_action_strings, None) on success.
    Returns ([], error_message) on failure.
    """
    try:
        data = json.loads(response_json)
        # Attempt to parse
        model = AgentTurnResponse(**data)
        action_strings = [a.to_engine_string() for a in model.actions]
        return action_strings, None
    except json.JSONDecodeError as e:
        return [], f"Invalid JSON generated: {str(e)}"
    except Exception as e:
        # Catches Pydantic validation errors
        return [], f"Validation Error: {str(e)}"
